exclude: "docs|node_modules|migrations|.git|.tox"
default_stages: [commit]
fail_fast: true

repos:
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: master
    hooks:
      - id: isort
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: master
    hooks:
      - id: trailing-whitespace
        files: (^|/).+\.(py|html|sh|css|js)$
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.6
    hooks:
      - id: forbid-crlf
      - id: remove-crlf
      - id: remove-tabs
  - repo: https://github.com/PyCQA/bandit
    rev: 1.6.2
    hooks:
      - id: bandit
  - repo: local
    hooks:
      - id: python-safety-dependencies-check
        name: safety
        entry: safety
        args: [check, --full-report, --file]
        language: system
        files: requirements.txt
        additional_dependencies: ["safety"]
      - id: flake8
        name: flake8
        entry: flake8
        language: python
        types: [python]
        args: ["--config=setup.cfg"]
  - repo: https://github.com/prettier/prettier
    rev: 1.19.1
    hooks:
      - id: prettier
        exclude: bitbucket-pipelines.yml
  - repo: git://github.com/awebdeveloper/pre-commit-tslint/
    rev: 0.0.2
    hooks:
      - id: tslint
        additional_dependencies: ["typescript", "tslint@6.0.0"]
  - repo: https://github.com/awebdeveloper/pre-commit-stylelint
    rev: 0.0.2
    hooks:
      - id: stylelint
        additional_dependencies:
          [
            "stylelint",
            "prettier",
            "stylelint-config-prettier",
            "stylelint-prettier",
          ]
