# Generated by Django 3.0.10 on 2020-10-20 05:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UID')),
                ('name', models.CharField(max_length=255, verbose_name='Store Name')),
                ('website', models.CharField(blank=True, max_length=255, null=True, verbose_name='Website')),
                ('logo', models.ImageField(blank=True, upload_to='uploads/stores/logo', verbose_name='Logo')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
